# Generated by Django 5.1.2 on 2026-01-05 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_section', models.BooleanField(default=True)),
                ('headline', models.CharField(default='About Us', max_length=200)),
                ('body_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_alt_text', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='CredibilitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_section', models.BooleanField(default=True)),
                ('headline', models.CharField(default="Growth You Can Trust, From Founders Who've Been There", max_length=200)),
                ('intro_paragraph', models.TextField(default="When a business looks effortless, it's because the right systems are working quietly in the background.")),
                ('primary_button_label', models.CharField(default='Start Your Profit Reclaim Today', max_length=100)),
                ('primary_button_url', models.URLField(default='#')),
                ('background_style', models.CharField(choices=[('light', 'Light'), ('neutral', 'Neutral Band'), ('texture', 'Texture')], default='neutral', max_length=50)),
            ],
            options={
                'verbose_name': 'Credibility Section',
                'verbose_name_plural': 'Credibility Section',
            },
        ),
        migrations.CreateModel(
            name='Differentiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_section', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FinalCTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_section', models.BooleanField(default=True)),
                ('headline', models.CharField(default='Get Your Business Assessment', max_length=200)),
                ('body_text', models.TextField(blank=True)),
                ('cta_label', models.CharField(default='Get Your Business Assessment', max_length=100)),
                ('cta_url', models.URLField(default='#')),
            ],
            options={
                'verbose_name': 'Final CTA Section',
                'verbose_name_plural': 'Final CTA Section',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_mission', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('copyright_text', models.CharField(default='© 2024 Scott & Shannon Kent. All rights reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_section', models.BooleanField(default=True)),
                ('emphasize_as_key_section', models.BooleanField(default=True)),
                ('headline', models.CharField(default='The Engine Behind Your Next Level of Growth', max_length=200)),
                ('subheadline', models.TextField(default='Reclaim up to 20+ hours a week and accelerate profit growth with AI-powered systems built for real businesses.')),
                ('body_text', models.TextField(default="Most founders rely on guesswork. You don't have time for that. Think of us as your revenue GPS—clear, direct, data-driven. This isn't about working harder; it's about making every move count.")),
                ('quote_text', models.TextField(default='AI should create freedom, not friction.')),
                ('quote_author', models.CharField(default='Scott & Shannon Kent', max_length=200)),
                ('primary_button_label', models.CharField(default='Book Your Diagnostic Assessment', max_length=100)),
                ('primary_button_url', models.URLField(default='#')),
                ('secondary_button_label', models.CharField(default='Download the Free Checklist', max_length=100)),
                ('secondary_button_url', models.URLField(default='#')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('image_alt_text', models.CharField(blank=True, max_length=200)),
                ('background_style', models.CharField(choices=[('gradient', 'Gradient'), ('texture', 'Texture'), ('solid', 'Solid')], default='gradient', max_length=50)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='MethodologyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_section', models.BooleanField(default=True)),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('outcome', models.CharField(help_text='The result: ...', max_length=300)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PainPointsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_section', models.BooleanField(default=True)),
                ('headline', models.CharField(default="Scaling doesn't break founders. Broken systems do.", max_length=200)),
                ('pain_intro_text', models.TextField(default="Growth shouldn't feel heavier the bigger you get. Every day you delay, time and profit leak out of your business.")),
                ('quote', models.TextField(blank=True)),
                ('quote_author', models.CharField(blank=True, max_length=200)),
                ('primary_button_label', models.CharField(default='Start Clearing the Bottlenecks Today', max_length=100)),
                ('primary_button_url', models.URLField(default='#')),
                ('background_style', models.CharField(choices=[('light', 'Light'), ('gradient', 'Gradient')], default='light', max_length=50)),
            ],
            options={
                'verbose_name': 'Pain Points Section',
                'verbose_name_plural': 'Pain Points Section',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_section', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('perfect_for', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fa-rocket)', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Scott & Shannon Kent', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('primary_cta_text', models.CharField(default='Book Diagnostic', max_length=100)),
                ('primary_cta_url', models.URLField(default='#')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SpeakingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_section', models.BooleanField(default=True)),
                ('headline', models.CharField(max_length=200)),
                ('body_text', models.TextField()),
                ('cta_label', models.CharField(default='Download Kit', max_length=100)),
                ('cta_url', models.URLField(default='#')),
                ('image', models.ImageField(blank=True, null=True, upload_to='speaking/')),
            ],
            options={
                'verbose_name': 'Speaking Section',
                'verbose_name_plural': 'Speaking Section',
            },
        ),
        migrations.CreateModel(
            name='WhoWeWorkWithSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_section', models.BooleanField(default=True)),
                ('headline', models.CharField(default='Not for Everyone — Designed for Founders Like You', max_length=200)),
                ('intro_text', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('quote_author', models.CharField(blank=True, max_length=200)),
                ('primary_button_label', models.CharField(default="See If You're the Right Fit", max_length=100)),
                ('primary_button_url', models.URLField(default='#')),
                ('background_style', models.CharField(choices=[('light', 'Light'), ('highlight', 'Highlighted Band')], default='highlight', max_length=50)),
            ],
            options={
                'verbose_name': 'Who We Work With Section',
                'verbose_name_plural': 'Who We Work With Section',
            },
        ),
        migrations.CreateModel(
            name='AuthorityBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_bullets', to='myApp.credibilitysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('column', models.IntegerField(choices=[(1, 'Column 1'), (2, 'Column 2'), (3, 'Column 3'), (4, 'Column 4')], default=1)),
                ('order', models.IntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='myApp.footer')),
            ],
            options={
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='myApp.footer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('result', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='myApp.painpointssection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='myApp.credibilitysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='myApp.whoweworkwithsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
